# Generated by Django 5.0.6 on 2024-05-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_username_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Приложите фото', null=True, upload_to='users/avatar/', verbose_name='Аватар'),
        ),
    ]
