# Generated by Django 5.0.6 on 2024-05-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(help_text='Выберите уроки', to='lesson.lesson', verbose_name='Уроки'),
        ),
    ]
