# Generated by Django 5.0.6 on 2024-05-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_lessons'),
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(blank=True, help_text='Выберите уроки', to='lesson.lesson', verbose_name='Уроки'),
        ),
    ]
