# Generated by Django 5.0.6 on 2024-06-09 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0005_course_owner_alter_course_lessons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма оплаты')),
                ('session_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='id сессии')),
                ('link', models.URLField(blank=True, max_length=512, null=True, verbose_name='Ссылка на оплату')),
                ('course', models.ForeignKey(help_text='Выберите курс', on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
                'ordering': ('id',),
            },
        ),
    ]
